conf/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponseNotFound
from django.urls import path, include

urlpatterns = [
    path('', include('djangoboard.urls')),
    path('admin/', admin.site.urls),

    # default password reset view could potentially give out our IP address, we don't want that
    path('accounts/password_reset/', lambda request: HttpResponseNotFound()),

    path('accounts/', include('django.contrib.auth.urls')),

    url(r'^captcha/', include('captcha.urls')),
]

djangoboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'djangoboard'
urlpatterns = [
    path('', views.home, name='homepage'),

    path('new_post', views.new_post, name='new_post'),
    path('new_thread', views.new_thread, name='new_thread'),

    path('post/<int:post_id>', views.post, name='post'),
    path('thread/<int:thread_id>', views.thread, name='thread'),
    path('thread/<int:thread_id>/reply_to/<int:replying_to>', views.thread, name='thread'),

    path('captcha', views.captcha, name='captcha'),

    path('profile', views.profile, name='profile'),
    path('delete', views.delete, name='delete'),

    path('help', TemplateView.as_view(template_name="djangoboard/help.html"), name='help'),
    path('success', TemplateView.as_view(template_name="djangoboard/success.html"), name='success'),

    path('<str:boardname>', views.board, name='board'),

]
if settings.DEBUG:  # otherwise should be configured using server software
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoboard/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone

__all__ = ['Board', 'IP', 'Post', 'Thread', 'Attachment']


class Board(models.Model):
    name = models.CharField(max_length=10, unique=True, primary_key=True)
    short_description = models.CharField(max_length=10, blank=True)
    description = models.CharField(max_length=500, blank=True)

    class Meta:
        permissions = (
            ('delete_posts', 'Delete posts'),

        )

    def __str__(self):
        return self.name


class IP(models.Model):
    address = models.CharField(max_length=44, primary_key=True)
    banned = models.BooleanField(default=False)


class AbstractPost(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=40, default='Anonymous', blank=True)
    subject = models.CharField(max_length=100, blank=True)
    comment = models.CharField(max_length=1000, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    ip = models.ForeignKey('IP', on_delete=models.CASCADE)


class Post(AbstractPost):
    thread = models.ForeignKey('Thread', on_delete=models.CASCADE, related_name='posts')
    replies = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='replies_to')
    attachments = GenericRelation('Attachment')

    class Meta:
        ordering = ['date']

    def __str__(self):
        return '%i:%s' % (self.id, self.comment[:15])


class Thread(AbstractPost):
    board = models.ForeignKey('Board', on_delete=models.CASCADE, related_name='threads')
    attachments = GenericRelation('Attachment')

    def __str__(self):
        return '%i:%s' % (self.id, self.comment[:15])


class Attachment(models.Model):
    file = models.FileField(blank=True, upload_to='uploads')
    mime = models.CharField(max_length=10, blank=True)

    content_type = models.ForeignKey(ContentType, related_name="content_type_attachments", on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    post = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return '%s:%s' % (self.mime, self.file.name)

djangoboard/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.utils.datastructures import MultiValueDict

from .models import *
from .templatetags.postmarkup import find_all_replies

__all__ = ['PostForm', 'ThreadForm', 'CaptchaForm']


class CaptchaForm(forms.Form):
    captcha = CaptchaField()


class AbstractPostForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('comment') and not cleaned_data.get('attachments_'):
            raise forms.ValidationError("Post is empty")

        if len(MultiValueDict(self.files).getlist('attachments_')) > 2:
            raise forms.ValidationError("Too many attachments_")

    def save(self):
        post = super().save(commit=False)
        post.ip = self.ip
        post.save()

        Attachment.objects.bulk_create(
            [Attachment(post=post, file=file, mime=file.content_type) for file in self.files.getlist('attachments_')])

        return post


class PostForm(AbstractPostForm):
    attachments_ = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Post

        fields = ['name', 'thread', 'subject', 'comment', 'thread', 'attachments_']
        widgets = {'thread': forms.HiddenInput(), 'comment': forms.Textarea()}

    def __init__(self, ip, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ip = ip

    def save(self):
        post = super().save()
        post.replies_to.add(*Post.objects.filter(id__in=find_all_replies(post.comment)))
        return post


class ThreadForm(AbstractPostForm):
    attachments_ = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Thread

        fields = ['name', 'subject', 'comment', 'board', 'attachments_']
        widgets = {'comment': forms.Textarea(), 'board': forms.HiddenInput()}

    def __init__(self, ip, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ip = ip

djangoboard/views.py
import guardian
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Prefetch, Max, Subquery, OuterRef, Case, When
from django.http import HttpRequest, HttpResponseBadRequest, HttpResponseForbidden, HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from djangoboard.utils import get_client_ip, human_required
from .forms import *
from .models import *


def home(request: HttpRequest):
    return render(request, 'djangoboard/home.html', {'boards': Board.objects.order_by('name')})


def board(request: HttpRequest, boardname: str):
    board_ = get_object_or_404(Board, name=boardname)

    query = Thread.objects.filter(board=board_) \
        .annotate(num_replies=Count('posts')) \
        .annotate(last_bumped=Case(
            # Threads have to be arranged by their last posts' dates or their own dates,
            # whichever is greater for each particular thread
            When(num_replies=0, then='date'),
            When(num_replies__gt=0, then=Max('posts__date'))
        ))\
        .order_by('-last_bumped') \
        .prefetch_related(Prefetch('posts',
                                   # Only a few of the latest posts need to be displayed
                                   queryset=Post.objects.filter(
                                       id__in=
                                       Subquery(
                                           Post.objects.filter(thread_id=OuterRef('thread_id')
                                                               ).values_list('id', flat=True)[
                                           :settings.DJANGOBOARD_POSTS_PREVIEWED]))
                                   ),
                          'attachments',
                          'posts__attachments'
                          )
    return render(request, 'djangoboard/board.html',
                  {'board': board_,
                   'threads': query,
                   'form': ThreadForm(ip=get_client_ip(request), initial={'board': boardname, }),
                   },
                  )


@human_required
def new_post(request: HttpRequest):
    ip = get_client_ip(request)

    if request.method == 'POST':
        form = PostForm(ip=ip, data=request.POST, files=request.FILES, )
        if form.is_valid():
            post = form.save()
            return HttpResponseRedirect(request.POST.get('next',
                                                         "%s#%s" % (
                                                             reverse('djangoboard:thread', args=[post.thread.id]),
                                                             post.id)
                                                         ))

    else:
        form = PostForm(ip=ip, initial={'thread': 1})
    return render(request, 'djangoboard/post_form.html',
                  {'form': form, })


@human_required
def new_thread(request: HttpRequest):
    ip = get_client_ip(request)

    if request.method == 'POST':
        form = ThreadForm(ip=ip, data=request.POST, files=request.FILES, )
        if form.is_valid():
            thread_ = form.save()
            # return HttpResponseRedirect(request.POST.get('next', reverse('djangoboard:success')))
            return HttpResponseRedirect(request.POST.get('next', reverse('djangoboard:thread', args=[thread_.id])))
    else:
        form = ThreadForm(ip=ip, initial={'board': 'b'})

    return render(request, 'djangoboard/thread_form.html',
                  {'form': form, 'next': reverse('djangoboard:homepage')})


def post(request: HttpRequest, post_id):
    post_ = get_object_or_404(Post, id=post_id)
    return redirect("%s#%s" % (reverse('djangoboard:thread', args=[post_.thread.id]), post_.id))


def thread(request: HttpRequest, thread_id, replying_to=None):
    thread_ = get_object_or_404(Thread, id=thread_id)
    posts = Post.objects.filter(thread=thread_).prefetch_related('attachments')
    board_ = thread_.board
    return render(request, 'djangoboard/thread.html',
                  {'form': PostForm(ip=get_client_ip(request),
                                    initial={
                                        'thread': thread_id,
                                        'comment': '' if replying_to is None else '>>%i' % replying_to
                                    }),
                   'thread': thread_,
                   'board': board_,
                   'posts': posts,
                   'displayed_post_ids': posts.values_list('id', flat=True),
                   'moderation': request.user.has_perm('delete_posts', board)}
                  )


def captcha(request: HttpRequest):
    if request.method == 'POST':
        form = CaptchaForm(request.POST)
        next_ = request.POST.get('next')
        if form.is_valid():
            request.session['human'] = True
            if next_:
                return redirect(next_)
    else:
        next_ = request.GET.get('next', reverse('djangoboard:captcha'))
        form = CaptchaForm()

    return render(request, 'djangoboard/captcha.html', {'form': form, 'next': next_})


@login_required
def profile(request: HttpRequest):
    moderated_boards = guardian.shortcuts.get_objects_for_user(request.user, 'delete_posts', Board)
    return render(request, 'djangoboard/profile.html', {'moderated_boards': moderated_boards})


@login_required
def delete(request: HttpRequest):
    if request.method != 'POST':
        return HttpResponseBadRequest()
    board = request.POST.get('board')
    if not board:
        return HttpResponseBadRequest()

    if not request.user.has_perm('delete_posts', board):
        return HttpResponseForbidden()
    Post.objects.filter(thread__in=Thread.objects.filter(board=board),
                        id__in=filter(lambda x: x.isdigit(), request.POST.keys())).delete()
    return HttpResponse("Success")

djangoboard/templates/djangoboard/attachments_snippet.html
{% load startswith %}
{% load static %}
<div class="attachments-container">
    {% load thumbnail %}
    {% for attachment in attachments %}

    <a href="{{attachment.file.url}}">
        {% if attachment.mime|startswith:"image" %}
        <img src="{% thumbnail attachment.file 100x100 crop %}" alt="attached picture"/>
        {% else %}
        <img src="{% static " djangoboard/generic_file.png" %}" alt="attached file"/>
        {% endif %}
    </a>
    {% endfor %}
</div>

djangoboard/templates/djangoboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tvoi ded{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'djangoboard/general.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    {% block head %}{% endblock %}
</head>

<body class="nojs">
<script src="{% static 'djangoboard/detect.js' %}"></script>
<header>
    <div class="topbar" align="center">
        {% if request.user.is_authenticated %}
        <a>{{ request.user }}</a>
        {% else %}
        <a href="{% url 'login' %}">login</a>
        {% endif %}

        <a href="{% url 'admin:index' %}">admin</a>
    </div>
    {%block header%}{%endblock%}
</header>
{% block content%}
<h1 align="center">¯\_(ツ)_/¯</h1>
{% endblock %}

</body>
</html>

djangoboard/templates/djangoboard/board.html
{% extends "djangoboard/base.html" %}
{% load static %}

{% block title %} {{ board.name }} - {{ board.short_description }} {% endblock %}

{%block head%}
<style>
.nojs #nondraggable-reveal {
  display: None;
}

.js #nondraggable-reveal{
  cursor: pointer;
  color: var(--accent-color);
  text-align: center;
  margin-left: auto;
  margin-right: auto;
}
</style>
 {%endblock%}


{%block header%} <h1 align="center"> {{board.short_description}} </h1>
<h3 align="center"> {{board.description}} </h3>
{%endblock%}

{% block content %}


<div onclick="toggle_visibility('nondraggable')" id="nondraggable-reveal">[New Thread]</div>
<script src="{% static 'djangoboard/toggle_visibility.js' %}"></script>
<div id="nondraggable" style="display: None;">

  {% include "djangoboard/thread_form_snippet.html" %}
</div>


<div class="all-posts-container">
  {% for thread in threads %}
  {% include "djangoboard/thread_snippet.html"%}
  {% for post in thread.posts.all %}
  {% load postmarkup %}
  <div class="post-container post-preview-container" id="post-{{post.id}}">

    <div class="post-info">
      <span class="post-subject">{{ post.subject }}</span>
      <span class="poster-name">{{ post.name }}</span>
      <span class="post-date">{{ post.date }}</span>
      <span class="post-id">
                    <a href="{% url 'djangoboard:thread' thread.id post.id %}#{{post.id}}">&gt;&gt;{{ post.id }}</a>
                </span>
    </div>
    {% include "djangoboard/attachments_snippet.html" with attachments=post.attachments.all%}
    <div class="post-comment">{{ post.comment|postmarkup }}</div>

  </div>
  {% endfor %}
  {% endfor %}
</div>
{% endblock %}

djangoboard/templates/djangoboard/captcha.html
{%block content%}
{% if request.session.human %}
<h1>You have a valid block bypass</h1>
{%endif%}
<form action="{% url 'djangoboard:captcha' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="hidden" value="{{next}}" name="next">
    <input type="submit" value="Submit"/>
</form>

{%endblock%}

djangoboard/templates/djangoboard/get_bypass.html
{% extends "djangoboard/base.html" %}

{% block title %} Action requires verification {% endblock %}
{% block content %}
<a href="{% url 'djangoboard:captcha' %}" target="_blank">Get block bypass</a>
{% endblock %}

djangoboard/templates/djangoboard/help.html
{% extends "djangoboard/base.html" %}

{% block content %}

<div class="help" style="text-align:center;">
    Markup:
    <ul>
        <li><span class="quote">&gt;green text</span></li>
        <li><span class="orange">&lt;orange text</span></li>
        <li>Reply to posts - <a>>>123</a></li>
        <li>Reply to threads - <a>>>>123</a></li>
    </ul>
</div>

{% endblock %}

djangoboard/templates/djangoboard/home.html
{% extends "djangoboard/base.html" %}
{% load static %}

{% block content %}
<h1 align="center">OwO</h1>
<h6 align="center">ÒwÓ</h6>


<div align="center" style="margin-top:100px;">
    {% for board in boards %}
    <p><a href="{% url 'djangoboard:board' board.name %}"> /{{board.name}}/ - {{board.short_description|default:"no description"}}</a></p>
    {% endfor %}
</div>

{% endblock %}

djangoboard/templates/djangoboard/post_form.html
{% extends "djangoboard/base.html" %}
{% block content %}
{% include "djangoboard/post_form_snippet.html" %}
{% endblock %}

djangoboard/templates/djangoboard/profile.html
{% extends "djangoboard/base.html" %}

{% block content %}

You can delete posts on the following boards:
{%for board in moderated_boards%}
</br>
<a href="{% url 'djangoboard:board' board.name%}">{{board.name}}</a>
{%endfor%}
{% endblock %}

djangoboard/templates/djangoboard/success.html
{% extends "djangoboard/base.html" %}
{% block title %} Post created {% endblock %}
{% block content %}
Post successfully created
{% endblock %}

djangoboard/templates/djangoboard/thread.html
{% extends "djangoboard/base.html" %}
{% load startswith %}
{% load static %}
{% load postmarkup %}

{% block title %} /{{thread.board.name}}/ - {{ thread.comment }} {% endblock %}
{% block header %}
<h1 align="center"><a href="{% url 'djangoboard:board' thread.board.name %}"> /{{board.name}}/ - {{board.short_description|default:"no description"}}</a></h1>
{% endblock %}
{% block content %}

<div id="draggable">
  <div id="draggable-header"><span class="close-button" onclick="toggle_visibility('draggable')">[x]</span>New Reply</div>
  {% include "djangoboard/post_form_snippet.html" %}
</div>
<script src="{% static 'djangoboard/draggable.js' %}"></script>
<script src="{% static 'djangoboard/toggle_visibility.js' %}"></script>


{% include "djangoboard/thread_snippet.html"%}
<form action="/delete" method="post">
  <input type="hidden" name="board" value="{{thread.board.name}}">
    {% csrf_token %}
    {% for post in posts %}
  <div class="post-container" id="{{post.id}}">
    <div class="post-info">
      {% if moderation %}
      <input type="checkbox" name="{{post.id}}">
            {% endif %}
      <span class="post-subject">{{ post.subject }}</span>
      <span class="poster-name">{{ post.name }}</span>
      <span class="post-date">{{ post.date }}</span>
      <span onclick="reply_to_post({{post.id}})" class="post-id">&gt;&gt;{{ post.id }}</span>
    </div>
    {% include "djangoboard/attachments_snippet.html" with attachments=post.attachments.all%}

    <div class="post-comment">{{ post.comment|postmarkup:displayed_post_ids }}</div>
    <div class="replies">
      {%for reply in post.replies.all%}
      <i>Replies: </i>{{post.id|get_post_link:displayed_post_ids}}
      {%endfor%}
    </div>
  </div>
  {% endfor %}
  {% if moderation %}
  <div class="bottomleft">
    <input type="submit" value="Delete">
    </div>
    {% endif %}
</form>

{% endblock %}

djangoboard/templates/djangoboard/thread_form.html
{% extends "djangoboard/base.html" %}
{% block content %}
{% include "djangoboard/thread_form_snippet.html" %}
{% endblock %}

djangoboard/templates/djangoboard/thread_form_snippet.html
<div class="post-form thread-form">
    <form action="{% url 'djangoboard:new_thread' %}" method="post" enctype="multipart/form-data" target="_blank">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Submit"/>
    </form>

</div>

djangoboard/templates/djangoboard/thread_snippet.html
{% load postmarkup %}
<div class="thread-container" id="thread-{{thread.id}}">

    <div class="post-info">
        <span class="post-subject">{{ thread.subject }}</span>
        <span class="poster-name">{{ thread.name }}</span>
        <span class="post-date">{{ thread.date }}</span>
        <span class="post-id"><a href="{% url 'djangoboard:thread' thread.id%}">&gt;&gt;&gt;{{ thread.id }}</a></span>
        <span class="thread-num-replies">{{ thread.num_replies }} repl{{ thread.num_replies|pluralize:"y,ies" }}</span>
    </div>
    {% include "djangoboard/attachments_snippet.html" with attachments=thread.attachments.all%}
    <div class="post-comment">{{ thread.comment|postmarkup }}</div>

</div>